_BASE_: "training.yaml"
MODEL:
  BACKBONE:
    FREEZE_AT: 6
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0002
  STEPS: (3000, 5000)
  MAX_ITER: 5001
  WARMUP_ITERS: 200
  CHECKPOINT_PERIOD: 5000
INPUT:
  FS:
    FEW_SHOT: True
VERSION: 2
