_BASE_: pvtv2-retinanet.yaml
MODEL:
  BACKBONE: 
    NAME: build_retinanet_fsod_pvtv2_fpn_backbone
  PROPOSAL_GENERATOR:
    NAME: CrossScalesRPN
  ROI_BOX_HEAD:
    NAME: MultiRelationBoxHead
VERSION: 2