_BASE_: pvtv2-retinanet-pvt5.yaml
MODEL:
  BACKBONE: 
    NAME: build_retinanet_pvtv2_fpn_backbone
  PROPOSAL_GENERATOR:
    NAME: AttentionRPN
  ROI_BOX_HEAD:
    NAME: PVT5MultiRelationBoxHead
VERSION: 2