MODEL:
  WEIGHTS: "./weights/pvt_v2_b2_li.pth"
  PVT:
    OUT_FEATURES: ["pvt4"]
  FPN:
    IN_FEATURES: []
  RPN:
    IN_FEATURES: ["pvt4"]
  ROI_HEADS:
    IN_FEATURES: ["pvt4"]
  BACKBONE:
    NAME: PyramidVisionTransformerV2
  ROI_BOX_HEAD:
    NAME: "PVT4BoxHead"
VERSION: 2