_BASE_: pvtv2-retinanet-pvt4.yaml
MODEL:
  BACKBONE: 
    NAME: FsodPyramidVisionTransformerV2
  PROPOSAL_GENERATOR:
    NAME: AttentionRPN
  ROI_BOX_HEAD:
    NAME: FsodPVT4MultiRelationBoxHead
VERSION: 2