MODEL:
  WEIGHTS: "./weights/twins_svt_small.pth"
  TWINS:
    OUT_FEATURES: ["stage4"]
  FPN:
    IN_FEATURES: []
  RPN:
    IN_FEATURES: ["stage4"]
  ROI_HEADS:
    IN_FEATURES: ["stage4"]
  BACKBONE:
    NAME: Twins
  ROI_BOX_HEAD:
    NAME: TwinsBoxHead # FastRCNNConvFCHead
    NUM_FC: 2
VERSION: 2