_BASE_: twinsv2-twins5.yaml
MODEL:
  BACKBONE: 
    NAME: Twins
    CROSS_ATTN: [False, False, False, False]
  PROPOSAL_GENERATOR:
    NAME: AttentionRPN
  ROI_BOX_HEAD:
    NAME: TwinsBoxHead # MultiRelationBoxHead
VERSION: 2