MODEL:
  ROI_HEADS:
    NAME: StandardROIHeads
  RPN:
    HEAD_NAME: StandardRPNHead
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0002
  STEPS: (110500, 143000)
  MAX_ITER: 143001
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 20000
VERSION: 2